### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#24]
It would be good if all source files could contain the proper license header in the file.  This greatly helps with license audits.

**Comment by VladimirChukharev** [comment]
I support the opinion that license audit is currently very complicated. This is true for all packages made by Enthought which I used (>5 packages).

Regarding envisage. The distributive envisage-4.5.1.tar.gz contains 3 files with license information:
```
 $ tar -tzvf distfiles/envisage-4.5.1.tar.gz | g license
-rw-r--r--  0 sjagoe sjagoe    442  3 Dec  2013 envisage-4.5.1/envisage/ui/workbench/action/images/image_LICENSE.txt
-rw-r--r--  0 sjagoe sjagoe    316  3 Dec  2013 envisage-4.5.1/envisage/ui/workbench/images/image_LICENSE.txt
-rw-r--r--  0 sjagoe sjagoe    748  3 Dec  2013 envisage-4.5.1/envisage/plugins/remote_editor/editor_plugins/editra/images/image_LICENSE.txt
```
The first file references to image_LICENSE_CP.txt file which is not included in the distributive. The referenced file is included in the mayavi distributive, and it is a copy of LGPL with a few introducing words.

The second file lists two files originating from Puthon Software Foundation and from Gael Varoquaux. Presumably, the first file has the Python license (PSFL). No information is given for the GV license. Some other packages from Enthought indicate that the GV license is an equivalent to BSD-like or BSD-licensed.

The third file claims that all files are authored by Enthought if not stated otherwise. Then it gives a list of files and their authors. Strangely, all listed files are authored by Enthought. To me, this list is redundant...

It would be nice to have all this information clarified. And even better, collected in the topmost folder in the distributive. The same is correct for many packages from Enthought, as has been mentioned already.

BTW, thanks a lot for your nice software products!
