### ISSUE TITLE
Need test eggs for python 3.9

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#286]
Fedora Rawhide now has python 3.9 so we need test eggs for 3.9.  Thanks!

**Comment by rahulporuri** [comment]
ref : similar to https://github.com/enthought/envisage/issues/213, fixed with https://github.com/enthought/envisage/pull/214

**Comment by mdickinson** [comment]
There's a slight danger in creating these eggs now, given that Python 3.9 is not yet released and something could still change that would invalidate the new eggs (e.g., bytecode changes).

Longer term, maybe we need to get away from the need for these pre-built eggs, or at least make use of them optional so that the test suite doesn't fail if they don't exist for a given version of Python.

**Comment by opoplawski** [comment]
Thanks!

**Comment by mdickinson** [comment]
> Longer term, maybe we need to get away from the need for these pre-built eggs, or at least make use of them optional so that the test suite doesn't fail if they don't exist for a given version of Python.

Finally done in #459.
