### ISSUE TITLE
Envisage/ETS roadmap

### ISSUE THREAD

**Issue by fbender** [enthought/envisage#73]
I'm looking into [porting an existing application](https://github.com/enthought/pyface/issues/219#issuecomment-225375258) to ETS/Envisage. In some Enthought repos, I currently see a lot of movement, while others look stale since years. It looks like Enthought is in a major overhaul process, and I'm a bit unsure how to proceed from here.

Is there a roadmap or any kind of plan for ETS and Envisage I can look into? I'm looking for feature development milestones and deprecation plans as well as a rough time estimate so I know what to embrace and what to avoid. I don't mind if the plan slips by months as I'll be working with the current (release) codebase – or should I start from master instead? Should I build a Pyface resp. TraitsUI app instead and later move it to envisage?

Can Envisage 4.5 be used together with v5 of Pyface and TraitsUI or should I use older versions of both?

**Comment by fbender** [comment]
Also, it'd be great if you get rid of stale branches in all your repos – most haven't been touched in years and some are obviously obsoleted (e.g. Python 3 compat branches while master is already Python 3 compatible). That would help a lot in terms of knowing what is going on in the projects and what we can expect to happen in the near future! Unfortunately, nobody outside Enthought can do that (other than "delete if no dev in > 6 months") otherwise I'd be be happy to help here. 😉

**Comment by corranwebster** [comment]
Envisage 4.5 should be able to be safely used with Pyface/TraitsUI 5+ with the caveat that 5 changes the default backend from Wx to Qt.  Project version numbers have been decoupled for a few years now.

The major effort we have been engaged recently is around Python 3 compatibility of the libraries we are using most frequently, and a bit more generally working off some of the technical debt that the libraries have accumulated over the years.  We aren't planning any major new changes to libraries at this time.

You should be reasonably safe following Master branches, since we don't merge unless tests are passing, and we endeavor to follow semantic versioning (which can mean that the versions appear to change faster than might otherwise be the case - eg. 99% of code will work as well on TraitsUI 4.5 as TraitsUI 5.1, but we had to bump major version numbers because the change of default backend has the potential to break currently working code. We frequently follow master in consulting projects if they contain bugfixes or features we need.

**Comment by mdickinson** [comment]
Closing as out of date.
